//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoAssistenciaTecnica
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SERVICO
    {
        public int id { get; set; }
        public string descricao { get; set; }
        public Nullable<int> cliente { get; set; }
        public Nullable<int> tecnico { get; set; }
    
        public virtual TB_CLIENTE TB_CLIENTE { get; set; }
        public virtual TB_TECNICO TB_TECNICO { get; set; }
    }
}
